### ISSUE TITLE
Exsception in SiMMLTable

### ISSUE THREAD

**Issue by bobrokrol** [keim/SiON#4]
![image](https://cloud.githubusercontent.com/assets/8383344/12538022/d3188ca2-c2d6-11e5-9df0-4d8515dae1f7.png)
org/si/sion/sequencer/SiMMLTable.as:216
Index out of bounds. I just copied latest soursecodes from the repo and used them as lib for MIDI player example.
SDK: Apache Flex 4.14
I've used this example as main file:
http://wonderfl.net/c/4IH3
[Main.as.txt](https://github.com/keim/SiON/files/102493/Main.as.txt)

**Comment by gunnbr** [comment]
Thanks for the report. I'll see what I can do to reproduce it.

**Comment by keim** [comment]
Thank you for the ticket. Fixed in the latest commit
